#! /usr/bin/env python3

import ibapi
import time

print(ibapi.__version__)

from ibapi.sync_wrapper import TWSSyncWrapper
from ibapi.contract import Contract
from ibapi.order_state import OrderState

# Check whether "commission" is one of OrderState class attributes:
orderState = OrderState()
print(f"OrderState class: {orderState.__dict__}")
print(f"'commission' is in orderState dict: {'commission' in orderState.__dict__.keys()}")

def aaplContract():

    contract = Contract()
    contract.symbol = "BMW"
    contract.exchange = "SMART"
    contract.currency = "EUR"
    contract.secType = "STK"

    return contract

contract = aaplContract()

client = TWSSyncWrapper()

client.connect_and_start('127.0.0.1', 7496, 0)

while True:
    if client.next_valid_id_value is None:
        continue
    else:
        print(client.next_valid_id_value)
        print(client.isConnected())

        portfolio = client.get_portfolio(account_code="DU6036902")
        print("Portfolio: ", portfolio)

        print(client.get_current_time())

        open_orders = client.get_open_orders()
        if open_orders:
            print(f"[+] Open Orders: {open_orders}")
        else:
            print(f"[+] No open orders currently")

        # This switches to delayed data
        client.reqMarketDataType(3)

        snapshot_data = client.get_market_data_snapshot(contract)
        if snapshot_data:
            print(f"[+] Snapshot data: {snapshot_data}")
        else:
            print(f"[+] No data available: {snapshot_data}")

        break
