#! /usr/bin/env python3

import ibapi
import time

print(ibapi.__version__)

from ibapi.sync_wrapper import TWSSyncWrapper
from ibapi.contract import Contract

def aaplContract():

    contract = Contract()
    contract.symbol = "BMW"
    contract.exchange = "SMART"
    contract.currency = "EUR"
    contract.secType = "STK"

    return contract

contract = aaplContract()

client = TWSSyncWrapper()

client.connect_and_start('127.0.0.1', 7496, 0)

while True:
    if client.next_valid_id_value is None:
        continue
    else:
        print(client.next_valid_id_value)
        print(client.isConnected())

        portfolio = client.get_portfolio(account_code="DU6036902")
        print("Portfolio: ", portfolio)

        print(client.get_current_time())

        print(client.get_open_orders())
        
        client.reqMarketDataType(3)

        print(client.get_market_data_snapshot(contract))

        break
